# Generated by Django 3.2.3 on 2021-05-29 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
